### ISSUE TITLE
How to disable usageStatistics in test environment? 

### ISSUE THREAD

**Issue by YashkaSurin** [nhnent/tui.calendar#259]
## Version
1.9.1

## Development Environment
nodeJs, jest

## Current Behavior

I'm using jest for testing. It breaks on importing tui calendar when trying to send statistics:

```
    TypeError: Cannot read property 'getItem' of undefined
      
      at Object.sendHostname (node_modules/tui-code-snippet/dist/tui-code-snippet.js:1708:37)
      at Object.<anonymous> (node_modules/tui-calendar/dist/tui-calendar.js:1498:10)
      at Object../src/index.js (node_modules/tui-calendar/dist/tui-calendar.js:1530:30)
      at __webpack_require__ (node_modules/tui-calendar/dist/tui-calendar.js:36:30)
      at node_modules/tui-calendar/dist/tui-calendar.js:100:18
      at node_modules/tui-calendar/dist/tui-calendar.js:103:10
      at webpackUniversalModuleDefinition (node_modules/tui-calendar/dist/tui-calendar.js:9:20)
      at Object.<anonymous> (node_modules/tui-calendar/dist/tui-calendar.js:16:3)
```

How can I prevent that? Setting global.tui.usageStatistics to false does not help.

**Comment by jungeun-cho** [comment]
@YashkaSurin 
We should support api which can disable usageStatistics.
I'm sorry for the inconvenience.
I'll try to respond as soon as possible.

**Comment by dongsik-yoo** [comment]
@YashkaSurin Why don't you mock localStorage? https://github.com/facebook/jest/issues/2098

**Comment by YashkaSurin** [comment]
@dongsik-yoo yes, that's what I came to in the end. I just thought there could be some way to do it using some component configuration that I had missed. Thanks.

**Comment by dongsik-yoo** [comment]
@YashkaSurin Is it in progress? Thanks in advance.

**Comment by YashkaSurin** [comment]
@dongsik-yoo mocking localStorage works for me.

**Comment by dongsik-yoo** [comment]
@YashkaSurin Good! It's helpful when using jest.
